spring:
  application:
    name: api-gateway
  server:
    port: "8080"
management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  routes:
    userprofile:
      url: http://172.23.239.114:8070
    book:
      url: http://172.23.239.114:8888
    user-login:
      url: http://172.23.239.114:8082
    recommendation:
      url: http://172.23.239.114:8092
    order:
      url: http://172.23.239.121:8081
    logistics:
      url: http://172.23.239.121:8086
    payment-service:
      url: http://172.23.239.123:9091
    cvrp-ms:
      url: http://172.23.239.123:8084
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    service-url:
      defaultZone: http://172.23.239.100:8761/eureka
