spring:
  application:
    name: api-gateway
  server:
    port: "9088"
management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  routes:
    userprofile:
      url: http://10.20.1.206:9073
    user-login:
      url: http://10.20.1.206:9074
    recommendation:
      url: http://10.20.1.206:9075
    order:
      url: http://10.20.1.206:9076
    book:
      url: http://10.20.1.206:9077
    cvrp-ms:
      url: http://10.20.1.206:9078
    payment-service:
      url: http://10.20.1.206:9079
    logistics:
      url: http://10.20.1.206:9080
    
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    service-url:
      defaultZone: http://10.20.1.206:9070/eureka
