spring:
  application:
    name: api-gateway
  server:
    port: "8080"
management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  routes:
    userprofile:
      url: http://10.20.1.206:8070
    book:
      url: http://10.20.1.206:8888
    user-login:
      url: http://10.20.1.206:8082
    recommendation:
      url: http://10.20.1.206:8092
    order:
      url: http://10.20.1.206:8081
    logistics:
      url: http://10.20.1.206:8086
    payment-service:
      url: http://10.20.1.206:9091
    cvrp-ms:
      url: http://10.20.1.206:8084
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    service-url:
      defaultZone: http://10.20.1.206:8761/eureka
