spring:
  application:
    name: api-gateway
  server:
    port: "8080"
management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  routes:
    userprofile-ms:
      url: http://172.23.239.114:8070
    book-ms:
      url: http://172.23.239.114:8888
    user-login:
      url: http://172.23.239.114:8082
    recommendation-ms:
      url: http://172.23.239.114:8092
    order-ms:
      url: http://172.23.239.121:8081
    logistics-ms:
      url: http://172.23.239.121:8086
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    service-url:
      defaultZone: http://172.23.239.100:8761/eureka
