spring:
  application:
    name: book
  data:
    mongodb:
      database: booksdb
      host: 10.20.1.97
      port: "27017"
      uri: mongodb://10.20.1.97/booksdb
      username: ""
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    service-url:
      defaultZone: http://172.23.239.100:8761/eureka
