spring:
  application:
    name: cvrp
  kafka:
    bootstrap-servers: 172.23.239.49:9092  
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    service-url:
      defaultZone: http://172.23.239.100:8761/eureka
