spring:
  application:
    name: logistics
  data:
    mongodb:
      database: logistics
      host: 10.20.1.97
      port: "27017"
      uri: mongodb://10.20.1.97/logistics
      username: ""
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    service-url:
      defaultZone: http://10.20.1.206:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
