spring:
  application:
    name: logistics-ms
  data:
    mongodb:
      database: logistics
      host: 172.23.239.124
      port: "27017"
      uri: mongodb://172.23.239.124/logistics
      username: ""
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    service-url:
      defaultZone: http://172.23.239.100:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
vehicle:
  capacity: "5670000"
  routeDurationLimit: "180"
slot:
  numberOfSlots: "3 "
  numberOfVehicles: "3"
  duration: "180"
  startTime: 0900,1300,1700
  endTime: "1200,1600,2000"
