
server:
  port: "8092"
spring:
  application:
    name: recommendation
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.23.239.100:8761/eureka
    register-with-eureka: "true"
    fetch-registry: "true"
