
server:
  port: "8092"
spring:
  data:
   neo4j:
     username: neo4j
     password: godeliver@12
     uri: bolt://172.23.239.124
  application:
    name: recommendation
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.23.239.100:8761/eureka
    register-with-eureka: "true"
    fetch-registry: "true"
