spring:
  application:
    name: userprofile
  data:
    mongodb:
      database: userprofile
      host: 172.23.239.124
      port: "27017"
      uri: mongodb://172.23.239.124/userprofile
      username: ""
  kafka:
    bootstrap-servers: 172.23.239.49:9092
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    service-url:
      defaultZone: http://172.23.239.100:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
